spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cardealer
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
    enabled: true

server:
  port: 8080