server:
  port: 8082

spring:
  application:
    name: storage-service
  datasource:
    url: jdbc:postgresql://localhost:5433/storage_db
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/car-dealership
          jwk-set-uri: http://localhost:8081/realms/car-dealership/protocol/openid-connect/certs